#!/usr/bin/env python
#
# bionumpy documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('..'))

import doctest
import bionumpy

# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.viewcode',
              'sphinx.ext.intersphinx',
              'sphinx.ext.autosummary',
              'sphinx.ext.doctest',
              'sphinx.ext.coverage',
              'sphinx_design',
              'sphinxcontrib.bibtex']

# for manuscript references
bibtex_bibfiles = ['manuscript/refs.bib']
bibtex_reference_style = 'label'
bibtex_encoding = 'latin'

doctest_global_setup = """
import bionumpy as bnp
import numpy as np
import os
if os.getcwd().endswith("docs_source"):
    os.chdir("../")
"""

doctest_default_flags = (
    doctest.ELLIPSIS
    | doctest.IGNORE_EXCEPTION_DETAIL
    | doctest.DONT_ACCEPT_TRUE_FOR_1
    | doctest.NORMALIZE_WHITESPACE)


# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
#source_suffix = '.rst'

# The master toctree document.
master_doc = 'menu'

# General information about the project.
project = 'bionumpy'
copyright = "2021, Knut Rand"
author = "Knut Rand"

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = bionumpy.__version__
# The full version, including alpha/beta/rc tags.
# release = bionumpy.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '_templates']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'bionumpydoc'

# -- Options for LaTeX output ------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'bionumpy',
     'bionumpy Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'bionumpy',
     'bionumpy Documentation',
     author,
     'bionumpy',
     'One line description of project.',
     'Miscellaneous'),
]

# autodoc

numpydoc_show_class_members = False
autodoc_default_flags = ['members', 'imported-member']
autodoc_mock_imports = ["numpy", "npstructures"]
autosummary_generate = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']


"""
extensions.append('autoapi.extension')
autoapi_type = 'python'
autoapi_dirs = ['../bionumpy/']
autoapi_keep_files = True
autoapi_root = 'autoapi/'
"""


# Latex manuscript settings


latex_documents = [
    ("manuscript/index", 'bionumpymanuscript.tex',
     'BioNumPy: Fast and easy analysis of biological data with Python',
     '', 'howto'),
]

text_add_secnumbers = False  # no numbering of sections

latex_elements = {
    "maketitle": "{\LARGE BioNumPy: Fast and easy analysis of biological data with Python}",
    #"maketitle": "\maketitle",
    "tableofcontents": "",
    'preamble': r'''
     \setcounter{secnumdepth}{0}
     % make phantomsection empty inside figures (citation bug: https://github.com/sphinx-doc/sphinx/issues/2134)
     \usepackage{etoolbox}
     \AtBeginEnvironment{figure}{\pretocmd{\hyperlink}{\protect}{}{}}
     \usepackage[T1]{fontenc}     % default is 'OT1'
    %\usepackage[utf8]{inputenc} % needed if you have an older TeX distribution
    \usepackage{lmodern}         % recommended
    \setlength\parindent{0pt}    % just for this example
    \usepackage[utf8]{inputenc}
 '''
}
