


analysis:
  intersect:
    tools: ["bionumpy", "bedtools"]
    output_file_ending: ".bed"
    runs:
      small: "nintervals100_nintervals101"
      big: "nintervals100000_nintervals110000"

  translate:
    tools: ["bionumpy", "biopython", "python", "biotite"]
    output_file_ending: ".fa"
    runs:
      small: "length150_nreads100"
      big: "length150_nreads1000000"

  reverse_complement:
    tools: ["bionumpy", "python", "biopython", "seqtk", "biotite"]
    output_file_ending: ".fa"
    runs:
      small: "length150_nreads100"
      big: "length150_nreads1000000"


  subsample:
    tools: ["python", "bionumpy", "seqtk"]
    runs:
      small: "length150_nreads200"
      big: "length150_nreads5000000"
