
name: build and test

on:
  push:
    branches: [ "dev-benchmarking"]


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: install npstructures dev
        if: github.ref != 'refs/heads/master'
        run: |
          pip install git+https://github.com/bionumpy/npstructures.git/@dev
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run benchmarks
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--cores 1 --use-conda --conda-cleanup-pkgs cache report_small.md validation_report_small.md'
          stagein: | # 'cd benchmarks' # additional preliminary commands to run (can be multiline)
            sudo apt-get install -y gfortran
            pip install -r requirements_dev.txt
            pip install .
            cd benchmarks
            

      - name: Save benchmarks results
        run: |
          git config --global user.name "github action"
          git add -f benchmarks/*report*.md
          git commit -am 'Benchmark results'

      - name: Push results to benchmark branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true
          branch: benchmarks
