
name: Manuscript

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Make manuscript
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'
          stagein: |  # additional preliminary commands to run (can be multiline)
           
            apt-get update && apt-get install make
            apt-get install libglib2.0-dev
            pip install -r requirements_dev.txt
            pip install .
            cd docs_source

      - name: Save benchmarks results
        run: |
          cp docs_source/_build/latex/bionumpymanuscript.pdf .
          git config --global user.email "github@action.com"
          git config --global user.name "github action"
          git config pull.rebase false
          git add -f bionumpymanuscript.pdf
          git commit -am 'New build of manuscript'
          git pull --allow-unrelated-histories -Xours origin benchmarks

      - name: Push results to benchmark branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true
          branch: benchmarks
