name: Upload to PyPI

on:
  # run after completed bump version
  workflow_run:
    workflows: [ "Bump version" ]
    branches: [ master ]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest
    # only run if bumpversion was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt 
          python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
