# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            os: [ubuntu-latest]
            python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install numpy 2
      run: pip install numpy==2.0.0rc1
    - name: Install npstructures dev
      if: github.ref != 'refs/heads/master'
      run: |
        pip install git+https://github.com/bionumpy/npstructures.git/@dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install biopython
        pip install -r requirements_dev.txt
        pip install .
    - name: Run pytest and doctest
      run: |
        ./run_tests

